@baseUrl = http://localhost:3000

# Usuários 

### Único usuário
GET {{baseUrl}}/usuarios/3

### Todos os usuários
GET {{baseUrl}}/usuarios/

### Usuários aleatórios
GET {{baseUrl}}/usuarios/aleatorios

### Todos os campos (primeira página)
GET {{baseUrl}}/usuarios?limite=10&pulo=0

### Apenas nome e sobrenome
GET {{baseUrl}}/usuarios?selecione=nome,sobrenome

### Campos específicos
GET {{baseUrl}}/usuarios?limite=10&pulo=0&selecione=nome,sobrenome,email

### Todos os usuários com campos específicos
GET {{baseUrl}}/usuarios?limite=0&selecione=nome,idade

### Segunda página com campos específicos
GET {{baseUrl}}/usuarios?limite=10&pulo=10&selecione=nome,email,telefone

### Filtro simples
GET {{baseUrl}}/usuarios/filtrar?chave=nome&valor=Lucas

### Filtro aninhado (JSON)
GET {{baseUrl}}/usuarios/filtrar?chave=cabelo.cor&valor=marrom

### Com paginação
GET {{baseUrl}}/usuarios/filtrar?chave=email&valor=joao@email.com&limite=10&pulo=0

### Com seleção de campos
GET {{baseUrl}}/usuarios/filtrar?chave=cabelo.cor&valor=preto&selecione=nome,email

### Retornar todos os registros filtrados
GET {{baseUrl}}/usuarios/filtrar?chave=idade&valor=25&limite=0

### Ordenar por nome
GET {{baseUrl}}/usuarios?ordenarPor=nome&ordem=crescente

### Ordenar por idade
GET {{baseUrl}}/usuarios?ordenarPor=idade&ordem=crescente

### Ordenar com limite
GET {{baseUrl}}/usuarios?limite=3&pulo=0&ordenarPor=email&ordem=desc

### Filtrar e ordenar
GET {{baseUrl}}/usuarios/filtrar?chave=sexo&valor=feminino&ordenarPor=nome&ordem=crescente


# Receitas

### Única receita
GET {{baseUrl}}/receitas/3

### Todas as receitas
GET {{baseUrl}}/receitas/

### Receitas aleatórias
GET {{baseUrl}}/receitas/aleatorias

### Todas as receitas com limite
GET {{baseUrl}}/receitas?limite=10&pulo=0

### Seleciona campos especificos
GET {{baseUrl}}/receitas?selecione=nome,ingredientes

### Seleciona campos especificos com limite
GET {{baseUrl}}/receitas?limite=3&selecione=nome,porcoes

### Ordenar
GET {{baseUrl}}/receitas?ordenarPor=nome&ordem=asc

### Ordenar com limite
GET {{baseUrl}}/receitas?limite=3&pulo=0&ordenarPor=culinaria&ordem=desc
